name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday
  workflow_dispatch:


jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    name: Sync NFI With Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to

      - name: Merge Upstream
        id: sync
        uses: bdougie/Fork-Sync-With-Upstream-action@fork
        with:
          upstream_repository: iterativv/NostalgiaForInfinity      # set the upstream repo
          upstream_branch: main   # set the upstream branch to merge from
          target_branch: main          # set the branch to merge to
      - name: Timestamp
        run: date