name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday
  workflow_dispatch:


jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    name: Sync NFI With Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to

      - name: Merge Upstream
        run: |
          git remote add upstream "https://github.com/iterativv/NostalgiaForInfinity"
          git fetch upstream main
          git pull upstream "main" --no-rebase
          git push origin "main"
          echo Merge completed!!!
      - name: Timestamp
        run: date